language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

database:
  - asn
  - city
  - country

format:
  - binary
  - csv

script:
  - ./maxmind.py --database=$database --format=$format
  - ls GeoLite2*
